/**
 *  Copyright 2009 The Regents of the University of California
 *  Licensed under the Educational Community License, Version 2.0
 *  (the "License"); you may not use this file except in compliance
 *  with the License. You may obtain a copy of the License at
 *
 *  http://www.osedu.org/licenses/ECL-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS"
 *  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 *  or implied. See the License for the specific language governing
 *  permissions and limitations under the License.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.03 at 02:10:42 PM CEST 
//

package org.opencastproject.media.mediapackage.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for audioType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;audioType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;device&quot; type=&quot;{}deviceType&quot;/&gt;
 *         &lt;element name=&quot;encoder&quot; type=&quot;{}encoderType&quot;/&gt;
 *         &lt;element name=&quot;channels&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *         &lt;element name=&quot;bitdepth&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *         &lt;element name=&quot;bitrate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot;/&gt;
 *         &lt;element name=&quot;samplingrate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audioType", propOrder = { "device", "encoder", "channels", "bitdepth", "bitrate", "samplingrate" })
public class AudioType {

  @XmlElement(required = true)
  protected DeviceType device;
  @XmlElement(required = true)
  protected EncoderType encoder;
  protected int channels;
  protected int bitdepth;
  protected float bitrate;
  protected int samplingrate;

  /**
   * Gets the value of the device property.
   * 
   * @return possible object is {@link DeviceType }
   * 
   */
  public DeviceType getDevice() {
    return device;
  }

  /**
   * Sets the value of the device property.
   * 
   * @param value
   *          allowed object is {@link DeviceType }
   * 
   */
  public void setDevice(DeviceType value) {
    this.device = value;
  }

  /**
   * Gets the value of the encoder property.
   * 
   * @return possible object is {@link EncoderType }
   * 
   */
  public EncoderType getEncoder() {
    return encoder;
  }

  /**
   * Sets the value of the encoder property.
   * 
   * @param value
   *          allowed object is {@link EncoderType }
   * 
   */
  public void setEncoder(EncoderType value) {
    this.encoder = value;
  }

  /**
   * Gets the value of the channels property.
   * 
   */
  public int getChannels() {
    return channels;
  }

  /**
   * Sets the value of the channels property.
   * 
   */
  public void setChannels(int value) {
    this.channels = value;
  }

  /**
   * Gets the value of the bitdepth property.
   * 
   */
  public int getBitdepth() {
    return bitdepth;
  }

  /**
   * Sets the value of the bitdepth property.
   * 
   */
  public void setBitdepth(int value) {
    this.bitdepth = value;
  }

  /**
   * Gets the value of the bitrate property.
   * 
   */
  public float getBitrate() {
    return bitrate;
  }

  /**
   * Sets the value of the bitrate property.
   * 
   */
  public void setBitrate(float value) {
    this.bitrate = value;
  }

  /**
   * Gets the value of the samplingrate property.
   * 
   */
  public int getSamplingrate() {
    return samplingrate;
  }

  /**
   * Sets the value of the samplingrate property.
   * 
   */
  public void setSamplingrate(int value) {
    this.samplingrate = value;
  }

}
