/**
 *  Copyright 2009 The Regents of the University of California
 *  Licensed under the Educational Community License, Version 2.0
 *  (the "License"); you may not use this file except in compliance
 *  with the License. You may obtain a copy of the License at
 *
 *  http://www.osedu.org/licenses/ECL-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS"
 *  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 *  or implied. See the License for the specific language governing
 *  permissions and limitations under the License.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.03 at 02:10:42 PM CEST 
//

package org.opencastproject.media.mediapackage.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for videoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;videoType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;device&quot; type=&quot;{}deviceType&quot;/&gt;
 *         &lt;element name=&quot;encoder&quot; type=&quot;{}encoderType&quot;/&gt;
 *         &lt;element name=&quot;resolution&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;scanType&quot; type=&quot;{}scanTypeType&quot;/&gt;
 *         &lt;element name=&quot;bitrate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot;/&gt;
 *         &lt;element name=&quot;frameRate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "videoType", propOrder = { "device", "encoder", "resolution", "scanType", "bitrate", "frameRate" })
public class VideoType {

  @XmlElement(required = true)
  protected DeviceType device;
  @XmlElement(required = true)
  protected EncoderType encoder;
  @XmlElement(required = true)
  protected String resolution;
  @XmlElement(required = true)
  protected ScanTypeType scanType;
  protected float bitrate;
  protected float frameRate;

  /**
   * Gets the value of the device property.
   * 
   * @return possible object is {@link DeviceType }
   * 
   */
  public DeviceType getDevice() {
    return device;
  }

  /**
   * Sets the value of the device property.
   * 
   * @param value
   *          allowed object is {@link DeviceType }
   * 
   */
  public void setDevice(DeviceType value) {
    this.device = value;
  }

  /**
   * Gets the value of the encoder property.
   * 
   * @return possible object is {@link EncoderType }
   * 
   */
  public EncoderType getEncoder() {
    return encoder;
  }

  /**
   * Sets the value of the encoder property.
   * 
   * @param value
   *          allowed object is {@link EncoderType }
   * 
   */
  public void setEncoder(EncoderType value) {
    this.encoder = value;
  }

  /**
   * Gets the value of the resolution property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getResolution() {
    return resolution;
  }

  /**
   * Sets the value of the resolution property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setResolution(String value) {
    this.resolution = value;
  }

  /**
   * Gets the value of the scanType property.
   * 
   * @return possible object is {@link ScanTypeType }
   * 
   */
  public ScanTypeType getScanType() {
    return scanType;
  }

  /**
   * Sets the value of the scanType property.
   * 
   * @param value
   *          allowed object is {@link ScanTypeType }
   * 
   */
  public void setScanType(ScanTypeType value) {
    this.scanType = value;
  }

  /**
   * Gets the value of the bitrate property.
   * 
   */
  public float getBitrate() {
    return bitrate;
  }

  /**
   * Sets the value of the bitrate property.
   * 
   */
  public void setBitrate(float value) {
    this.bitrate = value;
  }

  /**
   * Gets the value of the frameRate property.
   * 
   */
  public float getFrameRate() {
    return frameRate;
  }

  /**
   * Sets the value of the frameRate property.
   * 
   */
  public void setFrameRate(float value) {
    this.frameRate = value;
  }

}
