/**
 *  Copyright 2009 The Regents of the University of California
 *  Licensed under the Educational Community License, Version 2.0
 *  (the "License"); you may not use this file except in compliance
 *  with the License. You may obtain a copy of the License at
 *
 *  http://www.osedu.org/licenses/ECL-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS"
 *  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 *  or implied. See the License for the specific language governing
 *  permissions and limitations under the License.
 *
 */
package org.opencastproject.workflow.api;

import org.opencastproject.media.mediapackage.MediaPackage;

import java.util.Map;

import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * The result of a workflow operation.
 */
@XmlJavaTypeAdapter(WorkflowOperationResultImpl.Adapter.class)
public interface WorkflowOperationResult {
  /**
   * @return The media package that results from the execution of a workflow operation.
   */
  MediaPackage getResultingMediaPackage(); // TODO Support batch operations

  /**
   * 
   * @return A merged {@link Map} of properties, including the source properties as well as any resulting from execution
   * of a workflow operation.  In the case of key conflicts, properties generated by the workflow operation replace the
   * existing source properties.
   */
  Map<String, String> getResultingProperties();
  
  /**
   * Operations may optionally place a workflow into a paused state.
   * @return Whether this result should pause the workflow execution.
   */
  boolean isWait(); // TODO Support an arbitrary number of wait states
}
