/**
 *  Copyright 2009 The Regents of the University of California
 *  Licensed under the Educational Community License, Version 2.0
 *  (the "License"); you may not use this file except in compliance
 *  with the License. You may obtain a copy of the License at
 *
 *  http://www.osedu.org/licenses/ECL-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS"
 *  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 *  or implied. See the License for the specific language governing
 *  permissions and limitations under the License.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.03 at 02:10:42 PM CEST 
//

package org.opencastproject.media.mediapackage.jaxb;

import org.opencastproject.media.mediapackage.MediaPackage;
import org.opencastproject.media.mediapackage.MediaPackageImpl;

import org.w3c.dom.Document;

import java.io.StringWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for mediapackageType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;mediapackageType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;media&quot; type=&quot;{}mediaType&quot;/&gt;
 *         &lt;element name=&quot;metadata&quot; type=&quot;{}metadataType&quot;/&gt;
 *         &lt;element name=&quot;attachments&quot; type=&quot;{}attachmentsType&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;id&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;start&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}dateTime&quot; /&gt;
 *       &lt;attribute name=&quot;duration&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mediapackageType", propOrder = { "media", "metadata", "attachments" })
public class MediapackageType {

  @XmlElement(required = true)
  protected MediaType media;
  @XmlElement(required = true)
  protected MetadataType metadata;
  @XmlElement(required = true)
  protected AttachmentsType attachments;
  @XmlAttribute
  protected String id;
  @XmlAttribute
  protected XMLGregorianCalendar start;
  @XmlAttribute
  protected Integer duration;

  /**
   * Gets the value of the media property.
   * 
   * @return possible object is {@link MediaType }
   * 
   */
  public MediaType getMedia() {
    return media;
  }

  /**
   * Sets the value of the media property.
   * 
   * @param value
   *          allowed object is {@link MediaType }
   * 
   */
  public void setMedia(MediaType value) {
    this.media = value;
  }

  /**
   * Gets the value of the metadata property.
   * 
   * @return possible object is {@link MetadataType }
   * 
   */
  public MetadataType getMetadata() {
    return metadata;
  }

  /**
   * Sets the value of the metadata property.
   * 
   * @param value
   *          allowed object is {@link MetadataType }
   * 
   */
  public void setMetadata(MetadataType value) {
    this.metadata = value;
  }

  /**
   * Gets the value of the attachments property.
   * 
   * @return possible object is {@link AttachmentsType }
   * 
   */
  public AttachmentsType getAttachments() {
    return attachments;
  }

  /**
   * Sets the value of the attachments property.
   * 
   * @param value
   *          allowed object is {@link AttachmentsType }
   * 
   */
  public void setAttachments(AttachmentsType value) {
    this.attachments = value;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the start property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getStart() {
    return start;
  }

  /**
   * Sets the value of the start property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setStart(XMLGregorianCalendar value) {
    this.start = value;
  }

  /**
   * Gets the value of the duration property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getDuration() {
    return duration;
  }

  /**
   * Sets the value of the duration property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setDuration(Integer value) {
    this.duration = value;
  }
  
  public String toXml() throws Exception {
    StringWriter sw = new StringWriter();
    JAXBContext jaxbContext = JAXBContext.newInstance("org.opencastproject.media.mediapackage.jaxb");
    Marshaller marshaller = jaxbContext.createMarshaller();
    marshaller.marshal(this, sw);
    return sw.toString();
  }
    
  public static MediapackageType fromXml(Document mediaPackageXml) throws Exception {
    JAXBContext jaxbContext= JAXBContext.newInstance("org.opencastproject.media.mediapackage.jaxb");
    Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
    return unmarshaller.unmarshal(mediaPackageXml, MediapackageType.class).getValue();
  }

}
